name: Build Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current release
        id: reporelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: g0dsCookie
          repo: docker-dovecot
          excludes: prerelease, drafts

      - name: Set version
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "master" ]]; then
            VERSION=${{ steps.reporelease.outputs.release }}
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo $VERSION >ver
          IFS='_' read DOVECOT_VERSION SIEVE_VERSION
          rm -f ver
          echo "DOVECOT_VERSION=${DOVECOT_VERSION}" >>${GITHUB_ENV}
          echo "SIEVE_VERSION=${SIEVE_VERSION}" >>${GITHUB_ENV}

      - name: Setup docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: g0dscookie/dovecot,ghcr.io/g0dscookie/dovecot
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}},value=${{ env.DOVECOT_VERSION }}
            type=semver,pattern={{major}},value=${{ env.DOVECOT_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.DOVECOT_VERSION }}
            type=sha

      - name: Setup docker metadata
        id: metabloat
        uses: docker/metadata-action@v3
        with:
          images: g0dscookie/dovecot,ghcr.io/g0dscookie/dovecot
          flavor: |
            latest=auto
            suffix=-bloat,onlatest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}},value=${{ env.DOVECOT_VERSION }}
            type=semver,pattern={{major}},value=${{ env.DOVECOT_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.DOVECOT_VERSION }}
            type=sha

      - name: Setup QEMU for multiarch images
        uses: docker/setup-qemu-action@v1

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: base/
          platforms: linux/amd64,linux/arm64
          build-args: DOVECOT_VERSION=${{ env.DOVECOT_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: bloat/
          platforms: linux/amd64,linux/arm64
          build-args: |
            DOVECOT_VERSION=${{ env.DOVECOT_VERSION }}
            SIEVE_VERSION=${{ env.SIEVE_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metabloat.outputs.tags }}
          labels: ${{ steps.metabloat.outputs.labels }}